# This is the hyperparameter configuration file for FastSpeech2 v1.
# Please make sure this is adjusted for the LJSpeech dataset. If you want to
# apply to the other dataset, you might need to carefully change some parameters.
# This configuration performs 200k iters but a best checkpoint is around 150k iters.

###########################################################
#                FEATURE EXTRACTION SETTING               #
###########################################################
hop_size: 256            # Hop size.
format: "npy"


###########################################################
#              NETWORK ARCHITECTURE SETTING               #
###########################################################
fastspeech_params:
    n_speakers: 1
    hidden_size: 384
    num_hidden_layers: 4
    num_attention_heads: 2
    intermediate_size: 1024
    intermediate_kernel_size: 3
    num_duration_conv_layers: 2
    duration_predictor_filters: 256
    duration_predictor_kernel_sizes: 3
    num_mels: 80
    hidden_act: "mish"
    hidden_dropout_prob: 0.2
    attention_probs_dropout_prob: 0.1
    duration_predictor_dropout_probs: 0.5
    max_position_embeddings: 2048
    initializer_range: 0.02
    output_attentions: False
    output_hidden_states: False
    f0_energy_predictor_filters: 256
    f0_energy_predictor_kernel_sizes: 3
    f0_energy_predictor_dropout_probs: 0.5
    f0_kernel_size: 9
    energy_kernel_size: 9
    f0_dropout_rate: 0.5
    energy_dropout_rate: 0.5

###########################################################
#                  DATA LOADER SETTING                    #
###########################################################
batch_size: 16              # Batch size.
remove_short_samples: true  # Whether to remove samples the length of which are less than batch_max_steps.
allow_cache: true           # Whether to allow cache in dataset. If true, it requires cpu memory.
mel_length_threshold: 32    # remove all targets has mel_length <= 32
is_shuffle: true            # shuffle dataset after each epoch.
###########################################################
#             OPTIMIZER & SCHEDULER SETTING               #
###########################################################
optimizer_params:
    initial_learning_rate: 0.001
    end_learning_rate: 0.00005
    decay_steps: 150000          # < train_max_steps is recommend.
    warmup_proportion: 0.02
    weight_decay: 0.001


###########################################################
#                    INTERVAL SETTING                     #
###########################################################
train_max_steps: 200000               # Number of training steps.
save_interval_steps: 2000             # Interval steps to save checkpoint.
eval_interval_steps: 500              # Interval steps to evaluate the network.
log_interval_steps: 200               # Interval steps to record the training log.
###########################################################
#                     OTHER SETTING                       #
###########################################################
num_save_intermediate_results: 1  # Number of batch to be saved as intermediate results.
